/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evchargingstaionfinder;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.Random;
import javax.net.ssl.HttpsURLConnection;
/**
 *
 * @author Admin
 */
public class EVadminp extends javax.swing.JFrame {
    // Recipient's email ID needs to be mentioned.
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
     

    int OTP;
 
    /**
     * Creates new form EVadminp
     */
    public EVadminp() {
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2- getHeight()/2);
        conn= DBConecter.java_db();
    }
    
    public static void sendSms(String message,String number){
		try{		
		String apiKey="E8sYwxAyOaLXoW21tHhinpNzRfIbjPeqvgVUlBTd9K53ZDmScushzka4pcrJimYHLjDT9xZISoenEBMP";
		String sendId="FSTSMS";
		message=URLEncoder.encode(message, "UTF-8");
		String language="english";
		String route="p";
		String myUrl="https://www.fast2sms.com/dev/bulk?authorization="+apiKey+"&sender_id="+sendId+"&message="+message+"&language="+language+"&route="+route+"&numbers="+number;
		URL url=new URL(myUrl);
		HttpsURLConnection con=(HttpsURLConnection)url.openConnection();		
		con.setRequestMethod("GET");		
		con.setRequestProperty("User-Agent", "Mozilla/5.0");
		con.setRequestProperty("cache-control", "no-cache");
		System.out.println("Wait..............");		
		int code=con.getResponseCode();		
		System.out.println("Response code : "+code);		
		StringBuffer response=new StringBuffer();		
		BufferedReader br=new BufferedReader(new InputStreamReader(con.getInputStream()));		
		while(true){
			String line=br.readLine();
			if(line==null){
				break;
			}
			response.append(line);
		}		
		System.out.println(response);                                      
                                       JOptionPane.showMessageDialog(null,"Your OTP Send  successfully ^o^");		
		}catch (Exception e) {
			e.printStackTrace();
		}		
	}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sendotp = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        votp = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        mno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        remindData = new javax.swing.JRadioButton();
        refresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/14JPG.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Andalus", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Find EV Station");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 50));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Verify OTP :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 80, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("User Name :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 30));

        sendotp.setBackground(new java.awt.Color(0, 0, 0,80));
        sendotp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sendotp.setForeground(new java.awt.Color(255, 255, 255));
        sendotp.setText("Send OTP");
        sendotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendotpActionPerformed(evt);
            }
        });
        jPanel3.add(sendotp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 100, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Phone No :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, 30));

        votp.setBackground(new java.awt.Color(0, 0, 0,80));
        votp.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        votp.setForeground(new java.awt.Color(255, 255, 255));
        votp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        votp.setBorder(null);
        jPanel3.add(votp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, 30));

        uname.setBackground(new java.awt.Color(0, 0, 0,80));
        uname.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        uname.setForeground(new java.awt.Color(255, 255, 255));
        uname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uname.setBorder(null);
        jPanel3.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 100, 30));

        mno.setBackground(new java.awt.Color(0, 0, 0,80));
        mno.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mno.setForeground(new java.awt.Color(255, 255, 255));
        mno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mno.setBorder(null);
        jPanel3.add(mno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 100, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/7IMG.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 40, 50));

        login.setBackground(new java.awt.Color(255, 153, 102,80));
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/5IMG.png"))); // NOI18N
        login.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Verify & Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 3, 18))); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel3.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 160, 170));

        remindData.setBackground(new java.awt.Color(255, 201, 145));
        remindData.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        remindData.setText("Remind Me");
        remindData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remindDataActionPerformed(evt);
            }
        });
        jPanel3.add(remindData, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 100, -1));

        refresh.setBackground(new java.awt.Color(255, 201, 145));
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh.png"))); // NOI18N
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel3.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/13IMG.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 370));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/15JPG.jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(votp.getText())==OTP){
            JOptionPane.showMessageDialog(null,"Your OTP Valide \n Login successfully ^o^");   
            MainLogin j=new MainLogin();
            j.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Your OTP Is NOT  Valide (¬_¬) ");
        }                                    
    }//GEN-LAST:event_loginActionPerformed

    private void sendotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendotpActionPerformed
   
        Random rand = new Random();
        OTP=rand.nextInt(999999);
        System.out.println(OTP);        
        String Message="Welcom To EV Station Finder \nYour OTP is  "+ OTP ;		
        EVadminp.sendSms(Message, mno.getText());
    }//GEN-LAST:event_sendotpActionPerformed

    private void remindDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remindDataActionPerformed
              try{
            String sql="INSERT INTO admin"
                    + " (name,mobile,otp,votp,time) VALUES(?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1, uname.getText());
            pst.setString(2, mno.getText());
            pst.setString(3, votp.getText());
            pst.setString(4, votp.getText());
            pst.setString(5, new Date().toLocaleString());
            pst.execute();
           System.out.println("Data is Saved Successfully...");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
        try{
            rs.close();
            pst.close();
            conn.close();
        }catch(Exception e){ 
        }
        }                                             
    }//GEN-LAST:event_remindDataActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        uname.setText("");
        mno.setText("");
        votp.setText("");

    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EVadminp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EVadminp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EVadminp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EVadminp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EVadminp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton login;
    private javax.swing.JTextField mno;
    private javax.swing.JButton refresh;
    private javax.swing.JRadioButton remindData;
    private javax.swing.JButton sendotp;
    private javax.swing.JTextField uname;
    private javax.swing.JTextField votp;
    // End of variables declaration//GEN-END:variables
}
