/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evchargingstaionfinder;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class EVcsboker extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
     
    /**
     * Creates new form EVcsboker
     */
    public EVcsboker() {
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2- getHeight()/2);
        conn= DBConecter.java_db();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timePicker1 = new com.raven.swing.TimePicker();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mobino = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        auno = new javax.swing.JTextField();
        evno = new javax.swing.JTextField();
        dis = new javax.swing.JComboBox<>();
        st = new javax.swing.JComboBox<>();
        typec = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        euid = new javax.swing.JTextField();
        Map = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        TiemGUI = new javax.swing.JButton();
        date = new javax.swing.JTextField();
        saveReceipt = new javax.swing.JButton();
        home = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        printer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        timePicker1.setForeground(new java.awt.Color(94, 201, 226));
        timePicker1.setDisplayText(time);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("EV Charging Station ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Slot Booking");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 105, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Type OF Charger ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 120, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Mobile No");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Aadhar Card No");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("EV No");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 100, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("State ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Location Name");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 100, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Date");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 100, 30));

        mobino.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        mobino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobinoActionPerformed(evt);
            }
        });
        mobino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobinoKeyReleased(evt);
            }
        });
        jPanel2.add(mobino, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 160, 30));

        uname.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPanel2.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 160, 30));

        auno.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPanel2.add(auno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 160, 30));

        evno.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPanel2.add(evno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 160, 30));

        dis.setEditable(true);
        dis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select district ", "Mumbai", "Navi Mumbai", "Khalapur", "Lonavla", "Pune ", "Satara", "Kolhapur", "Sangli", "Ahmedhnagar", "Aurangabad " }));
        dis.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disActionPerformed(evt);
            }
        });
        jPanel2.add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 160, 30));

        st.setEditable(true);
        st.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 160, 30));

        typec.setEditable(true);
        typec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Type 1-J1772", "CCS - Type 1", "Type 2", "CCS - Type 1" }));
        jPanel2.add(typec, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 160, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Email ID");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, 20));

        euid.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPanel2.add(euid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 160, 30));

        Map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/mpalogo.png"))); // NOI18N
        Map.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapActionPerformed(evt);
            }
        });
        jPanel2.add(Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 30, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel13.setText("Time");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 100, 30));

        time.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPanel2.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 130, 30));

        TiemGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/time.png"))); // NOI18N
        TiemGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiemGUIActionPerformed(evt);
            }
        });
        jPanel2.add(TiemGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 30, 30));

        date.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 160, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 480));

        saveReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Donei.png"))); // NOI18N
        saveReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveReceiptActionPerformed(evt);
            }
        });
        jPanel1.add(saveReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 40, 40));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/home.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 40, 40));

        refresh.setBackground(new java.awt.Color(0, 0, 0,80));
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh.png"))); // NOI18N
        refresh.setBorder(null);
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 40, 40));

        printer.setBackground(new java.awt.Color(0, 0, 0,80));
        printer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/print.png"))); // NOI18N
        printer.setBorder(null);
        printer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printerActionPerformed(evt);
            }
        });
        jPanel1.add(printer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bookingImag.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mobinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobinoActionPerformed

    private void disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disActionPerformed
        // TODO add your handling code here:
        try{
            if (dis.getSelectedItem().equals("Mumbai")){
                st.removeAllItems();
                st.addItem("Jogeshwari west");
                st.addItem("Vile Parle west");
                st.addItem("Vikhroli");
                st.addItem("Anushakti Nagar");
                st.addItem("Chembur");
                st.addItem("Worli");
                st.addItem("Chhatrapati Shivaji Terminus Area");
                st.setSelectedItem(null);
            }
            else
            if (dis.getSelectedItem().equals("Navi Mumbai")){
                st.removeAllItems();
                st.addItem("Turbhe");
                st.addItem("Turbhe");
                st.addItem("Nerul");
                st.addItem("Kharghar");
                st.setSelectedItem(null);
            }
            else
            if (dis.getSelectedItem().equals("Khalapur")){
                st.removeAllItems();
                st.addItem("Unnamed Road");
                st.setSelectedItem(null);
            }
            else
            if(dis.getSelectedItem().equals("Lonavla")){
                st.removeAllItems();
                st.addItem("Varsoli");
                st.setSelectedItem(null);
            }
            else
            if (dis.getSelectedItem().equals("Pune")){
                st.removeAllItems();
                st.addItem("Baner");
                st.addItem("Aundh");
                st.addItem("Viman Nagar");
                st.addItem("Wagholi");
                st.setSelectedItem(null);
            }
            else
            if(dis.getSelectedItem().equals("Satara")){
                st.removeAllItems();
                st.addItem("Manik Nagar");
                st.addItem("Jambhgaon");
                st.setSelectedItem(null);
            }
            else
            if(dis.getSelectedItem().equals("Kolhapur")){
                st.removeAllItems();
                st.addItem("Shiroli");
                st.setSelectedItem(null);
            }
            else
            if(dis.getSelectedItem().equals("Sangli")){
                st.removeAllItems();
                st.addItem("Miraj");
                st.setSelectedItem(null);
            }
            else
            if(dis.getSelectedItem().equals("Ahmedhnagar")){
                st.removeAllItems();
                st.addItem("Imampur");
                st.setSelectedItem(null);
            }
            else
            if(dis.getSelectedItem().equals("Aurangabad")){
                st.removeAllItems();
                st.addItem("Talyachi Wadi");
                st.addItem("Mirzapur");
                st.setSelectedItem(null);
            }
        }catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_disActionPerformed

    private void mobinoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobinoKeyReleased
        // TODO add your handling code here:
        try{
            String sql="select * from userinfo where mobile = ?";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1, mobino.getText());
            rs=pst.executeQuery();
            
            String add1=rs.getString("uname");
            uname.setText(add1);
            
            
            String add2=rs.getString("aid");
            auno.setText(add2);
            
            
            String add3=rs.getString("email");
            euid.setText(add3);
            
            
            String add4=rs.getString("evno");
            evno.setText(add4);
            
            
        }catch(Exception e){
            
        } 
        finally{
        try{
            rs.close();
            pst.close();
        }catch(Exception e){
        
        }
        }        
    }//GEN-LAST:event_mobinoKeyReleased

    private void MapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapActionPerformed
        MapPage j=new MapPage();
        j.setVisible(true);
        this.dispose();                 
    }//GEN-LAST:event_MapActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        mobino.setText("");
        uname.setText("");
        auno.setText("");
        euid.setText("");
        evno.setText("");
        dis.setSelectedItem("");
        st.setSelectedItem("");
        date.setName(" ");
        date.setText("");
        time.setText("");
        typec.setSelectedItem("");
    }//GEN-LAST:event_refreshActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        HomePage j=new HomePage();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void saveReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveReceiptActionPerformed
                  try{
            String sql="INSERT INTO bookinfo"
                    + " (mno, uname , uaadhar , uemail , evno , state , lname , date , time , typec) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1, mobino.getText());
            pst.setString(2, uname.getText());
            pst.setString(3, auno.getText());
            pst.setString(4, euid.getText());
            pst.setString(5, evno.getText());
            String ma= (String) dis.getSelectedItem();
            String mo= (String) st.getSelectedItem();
            pst.setString(6, ma);
            pst.setString(7, mo);
            pst.setString(8, date.getText());
            pst.setString(9, time.getText());
            String ty= (String) typec.getSelectedItem();
            pst.setString(10, ty);
            pst.execute();
           JOptionPane.showMessageDialog(null,"Data is Saved Successfully...");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
        try{
            rs.close();
            pst.close();
            conn.close();
        }catch(Exception e){ 
        }
        }
    }//GEN-LAST:event_saveReceiptActionPerformed

    private void TiemGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiemGUIActionPerformed
        // TODO add your handling code here:
        timePicker1.showPopup(this, 100, 100);
    }//GEN-LAST:event_TiemGUIActionPerformed

    private void printerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printerActionPerformed
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");          
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                jPanel2.print(g2);
                return Printable.PAGE_EXISTS;
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
        }
        }
    }//GEN-LAST:event_printerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EVcsboker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EVcsboker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EVcsboker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EVcsboker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EVcsboker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Map;
    private javax.swing.JButton TiemGUI;
    private javax.swing.JTextField auno;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox<String> dis;
    private javax.swing.JTextField euid;
    private javax.swing.JTextField evno;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mobino;
    private javax.swing.JButton printer;
    private javax.swing.JButton refresh;
    private javax.swing.JButton saveReceipt;
    private javax.swing.JComboBox<String> st;
    private javax.swing.JTextField time;
    private com.raven.swing.TimePicker timePicker1;
    private javax.swing.JComboBox<String> typec;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
