/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evchargingstaionfinder;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Admin
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2- getHeight()/2);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        BookStation = new javax.swing.JButton();
        MapButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        UserData = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Exit.png"))); // NOI18N
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel2.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 80, 80));

        BookStation.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        BookStation.setText("Book Station");
        BookStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookStationActionPerformed(evt);
            }
        });
        jPanel2.add(BookStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 110, 80));

        MapButton.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        MapButton.setText("MAP Location");
        MapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapButtonActionPerformed(evt);
            }
        });
        jPanel2.add(MapButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 110, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/car.gif"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        UserData.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UserData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/profile.png"))); // NOI18N
        UserData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserDataActionPerformed(evt);
            }
        });
        jPanel2.add(UserData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/home.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 500));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookStationActionPerformed
        EVcsboker j=new EVcsboker();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BookStationActionPerformed
    private void MapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapButtonActionPerformed
        MapPage j=new MapPage();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MapButtonActionPerformed
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        singin j=new singin();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed
    private void UserDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserDataActionPerformed
        profilepage j=new profilepage();
        j.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_UserDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookStation;
    private javax.swing.JButton Exit;
    private javax.swing.JButton MapButton;
    private javax.swing.JButton UserData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
