/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evchargingstaionfinder;


import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MainLogin extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form MainLogin
     */
    public MainLogin() {
        initComponents();
        model.setSelectedItem(null);
        Toolkit toolkit=getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2- getHeight()/2);
        conn= DBConecter.java_db();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        evno = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        mno = new javax.swing.JTextField();
        ano = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        model = new javax.swing.JComboBox<>();
        maker = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Refresh = new javax.swing.JButton();
        userdata = new javax.swing.JButton();
        eid = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/EVVAL.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Personal Info :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EV NO");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 70, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mobile NO ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Aadhaar Card No ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 30));

        evno.setBackground(new java.awt.Color(0, 0, 0,80));
        evno.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        evno.setForeground(new java.awt.Color(255, 255, 255));
        evno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        evno.setBorder(null);
        jPanel2.add(evno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 170, 30));

        name.setBackground(new java.awt.Color(0, 0, 0,80));
        name.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setBorder(null);
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 130, 30));

        mno.setBackground(new java.awt.Color(0, 0, 0,80));
        mno.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        mno.setForeground(new java.awt.Color(255, 255, 255));
        mno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mno.setBorder(null);
        mno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mnoKeyReleased(evt);
            }
        });
        jPanel2.add(mno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 130, 30));

        ano.setBackground(new java.awt.Color(0, 0, 0,80));
        ano.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        ano.setForeground(new java.awt.Color(255, 255, 255));
        ano.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ano.setBorder(null);
        jPanel2.add(ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 130, 30));

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Info :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 120, 30));

        jLabel10.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 51));
        jLabel10.setText("EV");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 40));

        model.setBackground(new java.awt.Color(153, 153, 153));
        model.setEditable(true);
        model.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPanel2.add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 170, 30));

        maker.setBackground(new java.awt.Color(153, 153, 153));
        maker.setEditable(true);
        maker.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        maker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Company", "TATA Motors", "Mahindra", "Hyundai", "MG Motors", "Jaguar" }));
        maker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makerActionPerformed(evt);
            }
        });
        jPanel2.add(maker, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 170, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Model");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 70, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Company ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, 30));

        Refresh.setBackground(new java.awt.Color(153, 153, 153));
        Refresh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Refresh.setForeground(new java.awt.Color(255, 255, 255));
        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh.png"))); // NOI18N
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel2.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 30, 30));

        userdata.setBackground(new java.awt.Color(0, 0, 0,80));
        userdata.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        userdata.setForeground(new java.awt.Color(51, 255, 51));
        userdata.setText("Add ME ");
        userdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userdataActionPerformed(evt);
            }
        });
        jPanel2.add(userdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        eid.setBackground(new java.awt.Color(0, 0, 0,80));
        eid.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        eid.setForeground(new java.awt.Color(255, 255, 255));
        eid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        eid.setBorder(null);
        jPanel2.add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 130, 30));

        Password.setBackground(new java.awt.Color(0, 0, 0,80));
        Password.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.setBorder(null);
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 130, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email ID ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 102, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, 210));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 280, 140));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0,80));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/LAMP.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(285, 490));
        jLabel2.setMinimumSize(new java.awt.Dimension(285, 490));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 280, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void makerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makerActionPerformed
        // TODO add your handling code here:
        try{
            if (maker.getSelectedItem().equals("TATA Motors")){
            model.removeAllItems();
            model.addItem("E-Tigor");
            model.addItem("Nexon");
            model.setSelectedItem(null);
            }
            else
            if (maker.getSelectedItem().equals("Mahindra")){
            model.removeAllItems();            
            model.addItem("E-Verito");
            model.addItem("e20 Plus 8");
            model.setSelectedItem(null);
            }
            else
            if (maker.getSelectedItem().equals("Hyundai")){
            model.removeAllItems();            
            model.addItem("Kona");
            model.setSelectedItem(null);
            }
            else
            if(maker.getSelectedItem().equals("MG Motors")){
            model.removeAllItems();            
            model.addItem("ZS EV");
            model.setSelectedItem(null);
            }
            else
            if(maker.getSelectedItem().equals("Jaguar")){
            model.removeAllItems();           
            model.addItem("I-PACE");
            model.setSelectedItem(null);
            }        
        }catch(Exception e){
        System.out.println(e);
        }
    }//GEN-LAST:event_makerActionPerformed

    private void userdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userdataActionPerformed
          try{
            String sql="INSERT INTO userinfo"
                    + " (uname, mobile, aid, email,pass, make, model, evno) VALUES(?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1, name.getText());
            pst.setString(2, mno.getText());
            pst.setString(3, ano.getText());
            pst.setString(4, eid.getText());
            pst.setString(5, Password.getText());
            String ma= (String) maker.getSelectedItem();
            String mo= (String) model.getSelectedItem();
            pst.setString(6, ma);
            pst.setString(7, mo);
            pst.setString(8, evno.getText());
            pst.execute();
           JOptionPane.showMessageDialog(null,"Data is Saved Successfully...");
           singin j=new singin();
           j.setVisible(true);
           this.dispose();           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
        try{
            rs.close();
            pst.close();
            conn.close();
        }catch(Exception e){
        }
        }
    }//GEN-LAST:event_userdataActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        name.setText("");
        mno.setText("");
        ano.setText("");
        eid.setText("");
        maker.setSelectedItem("");
        model.setSelectedItem("");
        evno.setText("");
    }//GEN-LAST:event_RefreshActionPerformed

    private void mnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnoKeyReleased
        try{
            String sql="select * from userinfo where mobile = ?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, mno.getText());
            rs=pst.executeQuery();
            String add1=rs.getString("mobile");
            mno.setText(add1);
            String add2=rs.getString("uname");
            name.setText(add2);
        }catch(Exception e){
        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
            }
        }
    }//GEN-LAST:event_mnoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Password;
    private javax.swing.JButton Refresh;
    private javax.swing.JTextField ano;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField evno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> maker;
    private javax.swing.JTextField mno;
    private javax.swing.JComboBox<String> model;
    private javax.swing.JTextField name;
    private javax.swing.JButton userdata;
    // End of variables declaration//GEN-END:variables
}
