/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evchargingstaionfinder;

//import com.teamdev.jxbrowser.browser.Browser;
//import com.teamdev.jxbrowser.view.javafx.BrowserView;
import com.kingaspx.util.BrowserUtil;
import com.kingaspx.version.Version;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.events.ConsoleEvent;
import com.teamdev.jxbrowser.chromium.events.FinishLoadingEvent;
import com.teamdev.jxbrowser.chromium.events.LoadAdapter;
import com.teamdev.jxbrowser.chromium.events.TitleEvent;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;


import java.awt.BorderLayout;
import java.awt.Desktop;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class MapPage extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form MapPage
     */
    public MapPage() {
        initComponents();
        open_site();
        Toolkit toolkit=getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2- getHeight()/2);
        conn= DBConecter.java_db(); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAP = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reload = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        st = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        dis = new javax.swing.JComboBox<>();
        BookingFromP = new javax.swing.JButton();
        home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MAP.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Snap ITC", 2, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("EV");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel2.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Charging ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 50));

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 0, 22)); // NOI18N
        jLabel3.setText("Station");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 150, 30));

        reload.setBackground(new java.awt.Color(0, 0, 0,80));
        reload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh.png"))); // NOI18N
        reload.setBorder(null);
        reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadActionPerformed(evt);
            }
        });
        jPanel1.add(reload, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 40, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/12IMG.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 50));

        st.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select state ", "Maharashtra " }));
        jComboBox2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, 30));

        dis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select district ", "Mumbai", "Navi Mumbai", "Khalapur", "Lonavla", "Pune ", "Satara", "Kolhapur", "Sangli", "Ahmedhnagar", "Aurangabad " }));
        dis.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disActionPerformed(evt);
            }
        });
        jPanel1.add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 150, 30));

        BookingFromP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/backb.png"))); // NOI18N
        BookingFromP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingFromPActionPerformed(evt);
            }
        });
        jPanel1.add(BookingFromP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 40, 40));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/home.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MAP, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(MAP, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadActionPerformed
        browser.reload();
    }//GEN-LAST:event_reloadActionPerformed

    private void disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disActionPerformed
        // TODO add your handling code here:
        try{
            if (dis.getSelectedItem().equals("Mumbai")){
            st.removeAllItems();
            st.addItem("Jogeshwari west");
            st.addItem("Vile Parle west");
            st.addItem("Vikhroli");
            st.addItem("Anushakti Nagar");
            st.addItem("Chembur");
            st.addItem("Worli");
            st.addItem("Chhatrapati Shivaji Terminus Area");
            st.setSelectedItem(null);
            }
            else
            if (dis.getSelectedItem().equals("Navi Mumbai")){
            st.removeAllItems();            
            st.addItem("Turbhe");
            st.addItem("Turbhe");
            st.addItem("Nerul");
            st.addItem("Kharghar");
            st.setSelectedItem(null);
            }
            else
            if (dis.getSelectedItem().equals("Khalapur")){
            st.removeAllItems();            
            st.addItem("Unnamed Road");
            st.setSelectedItem(null);
            }
            else
            if(dis.getSelectedItem().equals("Lonavla")){
            st.removeAllItems();            
            st.addItem("Varsoli");
            st.setSelectedItem(null);
            }
            else
            if (dis.getSelectedItem().equals("Pune")){
            st.removeAllItems();            
            st.addItem("Baner");
            st.addItem("Aundh");
            st.addItem("Viman Nagar");
            st.addItem("Wagholi");
            st.setSelectedItem(null);
            }
            else
            if(dis.getSelectedItem().equals("Satara")){
            st.removeAllItems();            
            st.addItem("Manik Nagar");
            st.addItem("Jambhgaon");
            st.setSelectedItem(null);
            }
            else
            if(dis.getSelectedItem().equals("Kolhapur")){
            st.removeAllItems();            
            st.addItem("Shiroli");
            st.setSelectedItem(null);
            }
            else
            if(dis.getSelectedItem().equals("Sangli")){
            st.removeAllItems();            
            st.addItem("Miraj");
            st.setSelectedItem(null);
            }
            else
            if(dis.getSelectedItem().equals("Ahmedhnagar")){
            st.removeAllItems();            
            st.addItem("Imampur");
            st.setSelectedItem(null);
            }
            else
            if(dis.getSelectedItem().equals("Aurangabad")){
            st.removeAllItems();            
            st.addItem("Talyachi Wadi");
            st.addItem("Mirzapur");
            st.setSelectedItem(null);
            }
        }catch(Exception e){
        System.out.println(e);
        }
    }//GEN-LAST:event_disActionPerformed

    private void BookingFromPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingFromPActionPerformed
        EVcsboker j=new EVcsboker();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BookingFromPActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        HomePage j=new HomePage();
        j.setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        

        

      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookingFromP;
    private javax.swing.JPanel MAP;
    private javax.swing.JComboBox<String> dis;
    private javax.swing.JButton home;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reload;
    private javax.swing.JComboBox<String> st;
    // End of variables declaration//GEN-END:variables
    Browser browser;
    BrowserView view;
    private void open_site() {
        BrowserUtil.setVersion(Version.V6_22);
        browser = new Browser();
        view = new BrowserView(browser);
        MAP.add(view, BorderLayout.CENTER);
        browser.addTitleListener((TitleEvent evt) -> {
            jLabel1.setText("" + evt.getTitle());
        });
        browser.addConsoleListener((ConsoleEvent evt) -> {
            System.out.println("LOG: " + evt.getMessage());
        });
        browser.addLoadListener(new LoadAdapter() {
            @Override
            public void onFinishLoadingFrame(FinishLoadingEvent evt) {
                evt.getBrowser().setZoomLevel(-2);
            }
        });
        browser.loadURL("E:\\TY BcsCS\\project\\MAP folder\\sample.html");
    }
}
