/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evchargingstaionfinder;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class profilepage extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form profilepage
     */
    public profilepage() {
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2- getHeight()/2);
        conn= DBConecter.java_db();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ano = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        maker = new javax.swing.JComboBox<>();
        model = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        evno = new javax.swing.JTextField();
        Refresh = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Personal Info :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mobile NO ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 120, 30));

        mno.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        mno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mno.setBorder(null);
        mno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mnoKeyReleased(evt);
            }
        });
        jPanel1.add(mno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 170, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 120, 30));

        name.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setBorder(null);
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 170, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Aadhaar Card No ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 130, 30));

        ano.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        ano.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ano.setBorder(null);
        ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoActionPerformed(evt);
            }
        });
        jPanel1.add(ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 170, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email ID ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 120, 30));

        eid.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        eid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        eid.setBorder(null);
        jPanel1.add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 170, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 120, 30));

        Password.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.setBorder(null);
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 170, 30));

        jLabel10.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 51));
        jLabel10.setText("EV");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 40));

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Info :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 120, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Company ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 70, 30));

        maker.setBackground(new java.awt.Color(153, 153, 153));
        maker.setEditable(true);
        maker.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        maker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Company", "TATA Motors", "Mahindra", "Hyundai", "MG Motors", "Jaguar" }));
        maker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makerActionPerformed(evt);
            }
        });
        jPanel1.add(maker, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 170, 30));

        model.setBackground(new java.awt.Color(153, 153, 153));
        model.setEditable(true);
        model.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPanel1.add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 170, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Model");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 70, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EV NO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 70, 30));

        evno.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        evno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        evno.setBorder(null);
        jPanel1.add(evno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 170, 30));

        Refresh.setBackground(new java.awt.Color(153, 153, 153));
        Refresh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Refresh.setForeground(new java.awt.Color(255, 255, 255));
        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh.png"))); // NOI18N
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 30, 30));

        updateButton.setText("Update Record");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/evcarsystem.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 160, 150));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/profileimg.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 130));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/home.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 480, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/profileBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnoKeyReleased
        // TODO add your handling code here:
        try{
            String sql="select * from userinfo where mobile = ?";

            pst=conn.prepareStatement(sql);
            pst.setString(1, mno.getText());
            rs=pst.executeQuery();

            String add1=rs.getString("mobile");
            mno.setText(add1);

            String add2=rs.getString("uname");
            name.setText(add2);
            
            String add3=rs.getString("aid");
            ano.setText(add3);            
            
            String add4=rs.getString("email");
            eid.setText(add4);

            String add5=rs.getString("pass");
            Password.setText(add5);      
            
            String add6=rs.getString("make");
            maker.setSelectedItem(add6);
            
            String add7=rs.getString("model");
            model.setSelectedItem(add7);
            
            String add8=rs.getString("evno");
            evno.setText(add8);
            
                 
        }catch(Exception e){

        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){

            }
        }
    }//GEN-LAST:event_mnoKeyReleased

    private void makerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makerActionPerformed
        // TODO add your handling code here:
        try{
            if (maker.getSelectedItem().equals("TATA Motors")){
                model.removeAllItems();
                model.addItem("E-Tigor");
                model.addItem("Nexon");
                model.setSelectedItem(null);
            }
            else
            if (maker.getSelectedItem().equals("Mahindra")){
                model.removeAllItems();
                model.addItem("E-Verito");
                model.addItem("e20 Plus 8");
                model.setSelectedItem(null);
            }
            else
            if (maker.getSelectedItem().equals("Hyundai")){
                model.removeAllItems();
                model.addItem("Kona");
                model.setSelectedItem(null);
            }
            else
            if(maker.getSelectedItem().equals("MG Motors")){
                model.removeAllItems();
                model.addItem("ZS EV");
                model.setSelectedItem(null);
            }
            else
            if(maker.getSelectedItem().equals("Jaguar")){
                model.removeAllItems();
                model.addItem("I-PACE");
                model.setSelectedItem(null);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_makerActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        name.setText("");
        mno.setText("");
        ano.setText("");
        eid.setText("");
        Password.setText("");
        maker.setSelectedItem("");
        model.setSelectedItem("");
        evno.setText("");
    }//GEN-LAST:event_RefreshActionPerformed

    private void anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
          try{
            String val1=name.getText(); 
            String val2=mno.getText();
            String val3=ano.getText();
            String val4=eid.getText();
            String val5=Password.getText();
            String ma= (String) maker.getSelectedItem();
            String mo= (String) model.getSelectedItem();
            String val6=ma;
            String val7=mo;
            String val8=evno.getText();
            String sql="UPDATE userinfo SET  uname='"+val1+"', mobile='"+val2+"', aid='"+val3+
                    "', email='"+val4+"', pass='"+val5+"'"
                    + ", make='"+val6+"', model='"+val7+"', evno='"+val8+"' WHERE mobile='"+val2+"' ";
            pst =conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data is Uptdated Successfuly...");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try{
                rs.close();
                pst.close();
                conn.close();
            }catch(Exception e){
            }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        HomePage j=new HomePage();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profilepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profilepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profilepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profilepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profilepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Password;
    private javax.swing.JButton Refresh;
    private javax.swing.JTextField ano;
    private javax.swing.JButton back;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField evno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> maker;
    private javax.swing.JTextField mno;
    private javax.swing.JComboBox<String> model;
    private javax.swing.JTextField name;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
